Alms-136 [iOS] Implement batchUpdateDevicePosition in AmazonHttpClient
makeen-project/amazon-location-mobile-tracking-sdk-ios pull request #2
Opened 2024-05-27 12:52 UTC by zeeshanmakeen

Alms-120 [iOS] Implement getDevicePosition in AmazonHttpClient
Removed Amplify depedency
Fixed test cases

2024-05-27 13:40 UTC, olegfilimonov requested changes

2024-05-27 13:40 UTC, olegfilimonov commented on Package.swift
> +        .package(url: "https://github.com/makeen-project/amazon-location-mobile-auth-sdk-ios.git", branch: "ALMS-134_AmazonHttpClient"),
probably dont wanna commit this to main

2024-05-27 13:40 UTC, olegfilimonov commented on Package.swift
> +//                .product(name: "AWSLocationXCF", package: "aws-sdk-ios-spm"),
no commented out code. just delete it

2024-05-27 13:40 UTC, olegfilimonov commented on Sources/AWSTrackingSDKiOS/Tracking/Client/LocationTracker.swift
> +                throw NSError() //Error(response.description)
commented out code

2024-05-28 15:07 UTC, zeeshanmakeen commented on Package.swift
> +        .package(url: "https://github.com/makeen-project/amazon-location-mobile-auth-sdk-ios.git", branch: "ALMS-134_AmazonHttpClient"),
fixed

2024-05-28 15:07 UTC, zeeshanmakeen commented on Package.swift
> +//                .product(name: "AWSLocationXCF", package: "aws-sdk-ios-spm"),
fixed

2024-05-28 15:08 UTC, zeeshanmakeen commented on Sources/AWSTrackingSDKiOS/Tracking/Client/LocationTracker.swift
> +                throw NSError() //Error(response.description)
fixed

2024-05-28 15:14 UTC, merged